services:
  web:
    # Le dice a Compose: "Construí el contenedor usando el Dockerfile que está en esta misma carpeta (.)"
    build: .
    
    # NUEVO: Le decimos a Docker que se posicione directamente en la carpeta del backend
    working_dir: /app/Contenedor/backend
    
    # Al estar ya posicionados en el backend, el comando vuelve a ser limpio y corto
    command: python manage.py runserver 0.0.0.0:8000
    
    # LOS VOLÚMENES: El portal mágico con tu Windows
    volumes:
      - .:/app
      
    # Mapeo de puertos
    ports:
      - "8000:8000"