"""
Django settings for GoVehiculos project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f9db1!*j1s_p5lngxl@5!ktfqxia(bt!p881!mc36&wh%3-p85g78fd9g79djnoigd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Añadimos la dependencia de Django rest framework para crear la API REST
    'rest_framework',

    # Aplicaciones creadas para el proyecto
    'reservas',
    'vehiculos',
    # En vez de registrar la aplicación de usuarios con su nombre 'usuarios', registramos la configuración completa 'usuarios.apps.UsuariosConfig' para asegurarnos de que se ejecute el método ready() y se registren las señales correctamente. Esto es importante para que las señales se ejecuten en el momento adecuado, como después de migrar la base de datos, para crear los grupos y permisos necesarios.
    'usuarios.apps.UsuariosConfig',
]

# Indicamos que el modelo de usuario personalizado a utilizar es el modelo Usuario que definimos en la aplicación de usuarios, para que Django lo use en lugar del modelo de usuario por defecto de Django mediante que abstraemos auth_user que viene nativo, lo que nos permite agregar campos personalizados como el DNI y adaptar el sistema de autorización y autenticación a nuestras necesidades específicas. 
AUTH_USER_MODEL = 'usuarios.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GoVehiculos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GoVehiculos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-us'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# URL pública que se va a usar en el navegador (ej: localhost:8000/media/imagen.jpg)
MEDIA_URL = '/media/'

# Ruta física de la computadora donde Django va a crear la carpeta y guardar los archivos
MEDIA_ROOT = BASE_DIR / 'media'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.openapi.AutoSchema',
}

# Evita el redirect por defecto a /accounts/profile/ tras iniciar sesión.
LOGIN_REDIRECT_URL = '/api/v1/'
LOGOUT_REDIRECT_URL = '/api/v1/'