# Generated by Django 6.0.3 on 2026-06-06 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranquiciaTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito'), ('ambas', 'Ambas')], default='ambas', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_detalle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='nombre_titular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='ultimos_4_digitos',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='estadoreserva',
            name='nombre',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='reserva',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='pago',
            name='franquicia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.franquiciatarjeta'),
        ),
    ]
