# Generated by Django 6.0.3 on 2026-06-06 16:09

from django.db import migrations


def seed_franquicias(apps, schema_editor):
    FranquiciaTarjeta = apps.get_model('reservas', 'FranquiciaTarjeta')
    franquicias = [
        {'nombre': 'Visa', 'tipo': 'ambas'},
        {'nombre': 'MasterCard', 'tipo': 'ambas'},
        {'nombre': 'American Express', 'tipo': 'credito'},
    ]
    for data in franquicias:
        FranquiciaTarjeta.objects.get_or_create(nombre=data['nombre'], defaults={'tipo': data['tipo']})


def reverse_seed(apps, schema_editor):
    FranquiciaTarjeta = apps.get_model('reservas', 'FranquiciaTarjeta')
    FranquiciaTarjeta.objects.filter(nombre__in=['Visa', 'MasterCard', 'American Express']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_franquiciatarjeta_pago_metodo_detalle_pago_monto_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_franquicias, reverse_seed),
    ]
