# Generated by Django 6.0.3 on 2026-06-07 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_seed_franquicias'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='checkout_expira_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=15)),
                ('motivo', models.CharField(choices=[('cancelacion_usuario', 'Cancelación por el usuario'), ('cancelacion_sistema', 'Cancelación por el sistema'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('comprobante_transaccion', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reembolso', to='reservas.pago')),
            ],
        ),
    ]
