# Generated by Django 6.0.3 on 2026-06-08 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_reserva_checkout_expira_en_reembolso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reembolso',
        ),
    ]
